version: "3.3"
services:
  catcher:
    build: catcher/
    restart: unless-stopped
    volumes:
        - "./catcher/database.db:/app/database.db"
    env_file:
      - .env

  telegram-admin:
    build: telegram-admin/
    restart: unless-stopped
    env_file:
      - .env

  nginx:
    build: nginx/
    restart: unless-stopped
    ports:
        - "8080:8080"
    env_file:
      - .env
